kind: Service
apiVersion: v1
metadata:
  name: backend-service
  namespace: dzinternational
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 3200
