services:
  frontend:
    image: bryanchristy/dz-international-frontend:0.1
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    image: bryanchristy/dz-international-backend:1.0
    ports:
      - "3200:3200"
    depends_on:
      - postgres
      - mongo
    restart: unless-stopped

  postgres:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: d_z_international
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

volumes:
  pgdata:
  mongodata:
