services:
  traefik:
    command:
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"

  frontend:
    labels:
      - "traefik.http.routers.frontend.rule=Host(`${IP}`) && PathPrefix(`/`)"
      - "traefik.http.routers.frontend.tls.certresolver=le"

  backend:
    labels:
      - "traefik.http.routers.backend.rule=Host(`${IP}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
