services:
  traefik:
    image: traefik:v3.0
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--api.dashboard=true"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-certificates:/letsencrypt"
    networks:
      - dz-network

  frontend:
    image: ghcr.io/dark-n-dusky/dz-international-frontend:${FRONTEND_TAG}
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - dz-network

  backend:
    image: ghcr.io/dark-n-dusky/dz-international-backend:${BACKEND_TAG}
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.services.backend.loadbalancer.server.port=3200"
    ports:
      - "3200:3200"
      - "2525:2525"
      - "587:587"
    depends_on:
      - postgres
      - mongo
    restart: unless-stopped
    networks:
      - dz-network

  postgres:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: d_z_international
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # - "5432:5432"
    networks:
      - dz-network

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      # - "27017:27017"
    networks:
      - dz-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
    networks:
      - dz-network

volumes:
  pgdata:
  mongodata:
  traefik-certificates:

networks:
  dz-network:
