apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dzinternational
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        editor: vscode
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/dark-n-dusky/dz-international-frontend:latest-prod
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
