kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: dzinternational
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
